// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdByID = `-- name: GetAdByID :one
SELECT
    a.id,
    a.campaign_id,
    a.name,
    a.status,
    a.position_type,
    a.mid_roll_offset,
    a.priority,
    a.landing_page_url,
    a.media_source,
    a.media_url,
    a.media_mime,
    a.media_duration_ms,
    a.media_width,
    a.media_height,
    a.media_bitrate_kbps,
    a.created_at,
    a.updated_at,
    c.status    AS campaign_status,
    c.end_date  AS campaign_end_date
FROM ads a
JOIN campaigns c ON c.id = a.campaign_id
WHERE a.id = $1
`

type GetAdByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	CampaignID       pgtype.UUID        `json:"campaign_id"`
	Name             string             `json:"name"`
	Status           string             `json:"status"`
	PositionType     string             `json:"position_type"`
	MidRollOffset    *int32             `json:"mid_roll_offset"`
	Priority         int32              `json:"priority"`
	LandingPageUrl   *string            `json:"landing_page_url"`
	MediaSource      string             `json:"media_source"`
	MediaUrl         string             `json:"media_url"`
	MediaMime        string             `json:"media_mime"`
	MediaDurationMs  *int32             `json:"media_duration_ms"`
	MediaWidth       *int32             `json:"media_width"`
	MediaHeight      *int32             `json:"media_height"`
	MediaBitrateKbps *int32             `json:"media_bitrate_kbps"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CampaignStatus   string             `json:"campaign_status"`
	CampaignEndDate  pgtype.Timestamptz `json:"campaign_end_date"`
}

// Joins the ad with its campaign so callers can decide eligibility (campaign
// status, end_date) in a single round trip. Phase 3 will replace per-request
// DB reads with the in-memory snapshot loader.
func (q *Queries) GetAdByID(ctx context.Context, id pgtype.UUID) (GetAdByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdByID, id)
	var i GetAdByIDRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Status,
		&i.PositionType,
		&i.MidRollOffset,
		&i.Priority,
		&i.LandingPageUrl,
		&i.MediaSource,
		&i.MediaUrl,
		&i.MediaMime,
		&i.MediaDurationMs,
		&i.MediaWidth,
		&i.MediaHeight,
		&i.MediaBitrateKbps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CampaignStatus,
		&i.CampaignEndDate,
	)
	return i, err
}
