// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ad struct {
	ID               pgtype.UUID        `json:"id"`
	CampaignID       pgtype.UUID        `json:"campaign_id"`
	Name             string             `json:"name"`
	Status           string             `json:"status"`
	PositionType     string             `json:"position_type"`
	MidRollOffset    *int32             `json:"mid_roll_offset"`
	Priority         int32              `json:"priority"`
	LandingPageUrl   *string            `json:"landing_page_url"`
	MediaSource      string             `json:"media_source"`
	MediaUrl         string             `json:"media_url"`
	MediaMime        string             `json:"media_mime"`
	MediaDurationMs  *int32             `json:"media_duration_ms"`
	MediaWidth       *int32             `json:"media_width"`
	MediaHeight      *int32             `json:"media_height"`
	MediaBitrateKbps *int32             `json:"media_bitrate_kbps"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Advertiser struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Campaign struct {
	ID                     pgtype.UUID        `json:"id"`
	AdvertiserID           pgtype.UUID        `json:"advertiser_id"`
	Name                   string             `json:"name"`
	StartDate              pgtype.Timestamptz `json:"start_date"`
	EndDate                pgtype.Timestamptz `json:"end_date"`
	TotalBudgetImpressions *int32             `json:"total_budget_impressions"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type CapRule struct {
	ID                pgtype.UUID        `json:"id"`
	AdID              pgtype.UUID        `json:"ad_id"`
	MaxImpressions    int32              `json:"max_impressions"`
	TimeWindowSeconds int32              `json:"time_window_seconds"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
